"""Initial migration

Revision ID: 686e2dd340b3
Revises: 
Create Date: 2025-03-22 18:41:02.930243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686e2dd340b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('rent_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name')
    )
    op.drop_table('living_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('living_cost',
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('average_cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('location_name')
    )
    op.drop_table('city_cost')
    # ### end Alembic commands ###
